name: 'Setup Cloud Custodian'
description: 'Set up the latest version of cloud custodian and add the
   CLI to the PATH'
branding:
  icon: play-circle
  color: yellow
inputs:
  custodian-version:
    description: "Install a particular version of cloud custodian"
  include-azure:
    description: "Installs the c7n_azure extension if set to true"
    default: false
  include-gcp:
    description: "Installs the c7n_gcp extension if set to true"
    default: false
runs:
  using: "composite"
  steps:
  - shell: "bash"
    run: |
      python3 -m venv custodian
      source custodian/bin/activate
      VERSION_ARG="== ${{ inputs.custodian-version }}"
      pip install -Iv c7n $VERSION_ARG
      if [ "${{ inputs.include-azure }}" == true ]; then
        pip install -Iv c7n_azure $VERSION_ARG
      fi
      if [ "${{ inputs.include-gcp }}" == true ]; then
        pip install -Iv c7n_gcp $VERSION_ARG
      fi
      dir=$(pwd)
      cat << EOF > /usr/local/bin/custodian
      #!/bin/bash
      source ${dir}/custodian/bin/activate
      custodian "\$@"
      EOF
      chmod +x /usr/local/bin/custodian
