name: 'Setup Cloud custodian'
description: 'Set up the latest version of cloud custodian and add the
   CLI to the PATH'
branding:
  icon: play-circle
  color: yellow
inputs:
  include-azure:
    description: "Installs the c7n_azure extension if set to true"
    default: false
  include-gcp:
    description: "Installs the c7n_gcp extension if set to true"
    default: false
runs:
  using: "composite"
  steps:
  - shell: "bash"
    run: |
      python3 -m venv custodian
      source custodian/bin/activate
      pip install c7n
      if [ "${{ inputs.include-azure }}" == true ]; then
        pip install c7n_azure
      fi
      if [ "${{ inputs.include-gcp }}" == true ]; then
        pip install c7n_gcp
      fi
      dir=$(pwd)
      cat << EOF > /usr/local/bin/custodian
      #!/bin/bash
      source ${dir}/custodian/bin/activate
      custodian "\$@"
      EOF
      chmod +x /usr/local/bin/custodian
