name: Cloud Custodian
on:
  workflow_dispatch:

jobs:
  cloud-custodian:
    runs-on: ubuntu-latest
    name: Run cloud custodian
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: ./
      - name: Run
        run: custodian run -h