name: Cloud Custodian
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  cloud-custodian:
    runs-on: ubuntu-latest
    name: Run cloud custodian
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: ./
        with:
          include-azure: true
          include-gcp: true
          include-c7n-org: true
      - name: Run
        run: |
          custodian schema
          custodian version
          echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc
          source ~/.bashrc
          c7n-org --help
      - name: Install Specific Version
        uses: ./
        with:
          custodian-version: '0.9.7.0'
      - name: Run
        run: custodian version
