name: Cloud Custodian
on:
  workflow_dispatch:

jobs:
  cloud-custodian:
    runs-on: ubuntu-latest
    name: Run cloud custodian
    steps:
      - name: Install
        uses: ./
      - name: Run
        run: custodian -h