name: Cloud Custodian
on:
  workflow_dispatch:

jobs:
  cloud-custodian:
    runs-on: ubuntu-latest
    name: Run cloud custodian
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: ./
        with:
          custodian-version: '0.9.7.0'
      - name: Run
        run: custodian run -v
